#! /usr/bin/env python3
"""
    XOInvader
    ~~~~~~~~~
"""

import argparse

from xoinvader.game import create_game


def parse_args():
    """Parse incoming arguments."""
    parser = argparse.ArgumentParser()

    add_args = dict(
        no_sound=dict(
            default=False,
            action="store_true",
            help="Disable sounds."))

    parser.add_argument("-ns", "--no-sound", **add_args["no_sound"])

    args = parser.parse_args()
    return args


def main():
    """Start the game!"""
    args = parse_args()

    game = create_game(args.__dict__)
    return game.loop()

if __name__ == "__main__":
    main()
