#! /usr/bin/env python3
"""
    XOInvader
    ~~~~~~~~~
"""

from xoinvader.game import App

def main():
    """Start the game!"""
    game = App()
    game.loop()

if __name__ == "__main__":
    main()
